sonar.projectKey=nitin-projects_SIT-223-Task8.2C---DevSecOps
sonar.organization=nitin-projects
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=coverage/lcov.info
